### ISSUE TITLE
Possibility to togge the icon

### ISSUE THREAD

**Issue by SolvosNSA** [Mcpoowl/FaviconBadge#1]
Not so much an issue as a request, but I would like to be able to ''toggle'' the Badge. I'd like to show the amount of new messages/tasks a person has, but when this person has 0 tasks the Badge should be gone (and re-appear when a new message/task becomes available).

Is something like this even possible without refreshing the pages?

**Comment by Mcpoowl** [comment]
Should be doable. Actually it should work automatically if I use an Integer to set the badge content.
So if the microflow is 0 (as an Integer) it would automatically hide the badge. However, since I always ask for a String, the value would be '0' is my guess.

So your request is possible, I'll have to have a look on what the best way to implement this is. I could always try to parse the String result to an Integer and add that to the badge.

I'll keep you updated. Thanks for the request!

**Comment by SolvosNSA** [comment]
It might also be my setup, currently using a snippet in my layouts which retrieves a ‘’badge’’ entity (which I only have 1 on my database) With a scheduled event running every minute I retrieved this object and updated it and refreshed, but it does not seem to refresh the badge properly.

Met vriendelijke groet,

Niels van de Sande

**Comment by Mcpoowl** [comment]
That's weird (and a seperate issue from the request that you posted) If you look at the testproject included in this repo, you can see the badge working.

**Comment by Mcpoowl** [comment]
Solved in v1.1. Submitted to the appstore!
:-)

**Comment by SolvosNSA** [comment]
Works like a charm! Currently working on a customer service app and this is just perfect, thanks ☺

Met vriendelijke groet,

Niels van de Sande

[SOL Email Signature Niels]

**Comment by Mcpoowl** [comment]
Awesome to hear!
