### ISSUE TITLE
Background updating objects with schedule events does not seem to work

### ISSUE THREAD

**Issue by SolvosNSA** [Mcpoowl/FaviconBadge#2]
Background updating objects with schedule events does not seem to work (might be underlying mendix issue?)

Setup:
In the sample project I have done the following:
Make color persistable (and adjust the creation to be persisted to database)
Create a SE that runs every 20 seconds to do the ''Badge +1"
Stay on the Dataview - Editable page.

The BadgeIcon widget does not get updated (The dataview itself does not even reflect changes in the number/color code). When manually pressing the Badge +1 button it does add the +1 (And we can see that all the SE's that have been ran in the meanwhile actually did happen) and the Badge gets updated. 

I hope i've explained it clearly enough for you to understand what I mean. Like I said it might be an underlying issue with mendix updating/refreshing because the data view does not seem to get refreshed either (untill you hit the button)

**Comment by Mcpoowl** [comment]
Hi Niels,

I'm not sure if I'll be able to solve this issue, since as you say yourself the Dataview Object doesn't refresh, and that's currently the way the badge gets refreshed.

However, I do plan to implement a feature like the Microflow timer, so you can re-execute the microflow in the widget every 'X' seconds.

Not sure when that'll be finished though!

**Comment by SolvosNSA** [comment]
That’d be awesome.

It is very much a ‘’nice to have’’ feature (but a very nice one at that) so eagerly awaiting any updates ☺

Thanks for the fast replies

**Comment by Mcpoowl** [comment]
Glad to see the widget is helpfull, I'll keep you posted. Meanwhile, we can discuss this feature in #3
